const StudentAttendanceData = {
  Attendance: [
    {
      id: 1,
      date: "Dec 11, 2024",
      day: "Monday",
      checkin: "9:00 AM",
      checkout: "5:00 PM",
      workHours: "8 hours",
      status: "Work from Office",
    },
    {
      id: 2,
      date: "Dec 12, 2024",
      day: "Tuesday",
      checkin: "10:00 AM",
      checkout: "6:00 PM",
      workHours: "8 hours",
      status: "Late Arrival",
    },
    {
      id: 3,
      date: "Dec 13, 2024",
      day: "Wednesday",
      checkin: "00:00",
      checkout: "00:00",
      workHours: "0 hours",
      status: "Absent",
    },
    {
      id: 4,
      date: "Dec 14, 2024",
      day: "Thursday",
      checkin: "9:30 AM",
      checkout: "4:30 PM",
      workHours: "7 hours",
      status: "Late Arrival",
    },
    {
      id: 5,
      date: "Dec 15, 2024",
      day: "Friday",
      checkin: "8:45 AM",
      checkout: "4:45 PM",
      workHours: "8 hours",
      status: "Work from Office",
    },
    {
      id: 6,
      date: "Dec 16, 2024",
      day: "Saturday",
      checkin: "00:00",
      checkout: "00:00",
      workHours: "0 hours",
      status: "Absent",
    },
    {
      id: 7,
      date: "Dec 17, 2024",
      day: "Sunday",
      checkin: "00:00",
      checkout: "00:00",
      workHours: "0 hours",
      status: "Absent",
    },
    {
      id: 8,
      date: "Dec 18, 2024",
      day: "Monday",
      checkin: "9:15 AM",
      checkout: "5:15 PM",
      workHours: "8 hours",
      status: "Work from Home",
    },
    {
      id: 9,
      date: "Dec 19, 2024",
      day: "Tuesday",
      checkin: "10:00 AM",
      checkout: "6:00 PM",
      workHours: "8 hours",
      status: "Late Arrival",
    },
    {
      id: 10,
      date: "Dec 23, 2024",
      day: "Wednesday",
      checkin: "9:00 AM",
      checkout: "5:00 PM",
      workHours: "8 hours",
      status: "Work from Office",
    },
  ],
};

export default StudentAttendanceData;
