# Generated by Django 5.2 on 2025-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_services", "0002_instructorprofile_studentprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscontrol",
            name="location",
            field=models.CharField(
                choices=[("gate", "Gate"), ("dormitory", "Dormitory")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="cafeteriatransaction",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                max_length=50,
            ),
        ),
    ]
