# Generated by Django 5.2 on 2025-05-31 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_services", "0003_alter_accesscontrol_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrol",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="cafeteriatransaction",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="accesscontrol",
            name="rfid_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_services.rfidtag",
            ),
        ),
        migrations.AlterField(
            model_name="cafeteriatransaction",
            name="rfid_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_services.rfidtag",
            ),
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("otp_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_services.student",
                    ),
                ),
            ],
        ),
    ]
