# Generated by Django 5.1.7 on 2025-04-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="instructor_images/"
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="rfid_tag",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_services.rfidtag",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="student_images/"),
        ),
    ]
