const ClassAttendanceData = {
  studentData: [
    {
      id: 1,
      studentName: "John Doe",
      profileImage: "../assets/JohnProfile.png",
      className: "Math 101",
      date: "2025-01-10",
      day: "Monday",
      checkin: "08:30 AM",
      status: "Present",
    },
    {
      id: 2,
      studentName: "Jane Smith",
      profileImage: "../assets/JaneProfile.png",
      className: "Math 101",
      date: "2025-01-10",
      day: "Monday",
      checkin: "08:32 AM",
      status: "Late",
    },
    {
      id: 3,
      studentName: "Michael Johnson",
      profileImage: "../assets/MichaelProfile.png",
      className: "Physics 201",
      date: "2025-01-11",
      day: "Tuesday",
      checkin: "09:00 AM",
      status: "Present",
    },
    {
      id: 4,
      studentName: "Emily Davis",
      profileImage: "../assets/EmilyProfile.png",
      className: "Physics 201",
      date: "2025-01-11",
      day: "Tuesday",
      checkin: "09:10 AM",
      status: "Absent",
    },
    {
      id: 5,
      studentName: "Chris Brown",
      profileImage: "../assets/ChrisProfile.png",
      className: "Chemistry 301",
      date: "2025-01-12",
      day: "Wednesday",
      checkin: "10:15 AM",
      status: "Present",
    },
    {
      id: 6,
      studentName: "Jessica White",
      profileImage: "../assets/JessicaProfile.png",
      className: "Chemistry 301",
      date: "2025-01-12",
      day: "Wednesday",
      checkin: "10:20 AM",
      status: "Late",
    },
    {
      id: 7,
      studentName: "Daniel Martinez",
      profileImage: "../assets/DanielProfile.png",
      className: "History 101",
      date: "2025-01-13",
      day: "Thursday",
      checkin: "11:00 AM",
      status: "Present",
    },
    {
      id: 8,
      studentName: "Sarah Wilson",
      profileImage: "../assets/SarahProfile.png",
      className: "History 101",
      date: "2025-01-13",
      day: "Thursday",
      checkin: "11:05 AM",
      status: "Present",
    },
    {
      id: 9,
      studentName: "Kevin Lee",
      profileImage: "../assets/KevinProfile.png",
      className: "English 202",
      date: "2025-01-14",
      day: "Friday",
      checkin: "08:45 AM",
      status: "Absent",
    },
    {
      id: 10,
      studentName: "Laura Gonzalez",
      profileImage: "../assets/LauraProfile.png",
      className: "English 202",
      date: "2025-01-14",
      day: "Friday",
      checkin: "08:50 AM",
      status: "Late",
    },
    {
      id: 11,
      studentName: "James Anderson",
      profileImage: "../assets/JamesProfile.png",
      className: "Computer Science 401",
      date: "2025-01-15",
      day: "Saturday",
      checkin: "12:00 PM",
      status: "Present",
    },
    {
      id: 12,
      studentName: "Olivia Martinez",
      profileImage: "../assets/OliviaProfile.png",
      className: "Computer Science 401",
      date: "2025-01-15",
      day: "Saturday",
      checkin: "12:05 PM",
      status: "Present",
    },
    {
      id: 13,
      studentName: "Robert Brown",
      profileImage: "../assets/RobertProfile.png",
      className: "Biology 102",
      date: "2025-01-16",
      day: "Sunday",
      checkin: "02:00 PM",
      status: "Absent",
    },
    {
      id: 14,
      studentName: "Sophia Miller",
      profileImage: "../assets/SophiaProfile.png",
      className: "Biology 102",
      date: "2025-01-16",
      day: "Sunday",
      checkin: "02:10 PM",
      status: "Present",
    },
  ],
};

export default ClassAttendanceData;
